### ISSUE TITLE
Error "HTML element not located. Shutting down."

### ISSUE THREAD

**Issue by nicolas-porta** [hvignolo87/tito#6]
Hello !
First of all thanks a lot for putting effort into building this automation workflow. 
I've been trying to use it for the past few days but after the login, I always get "HTML element not located. Shutting down." (line 374 of Browser.py).
Any clues why this error happen??
I appreciate any help, as taking an appointment using regular methods is impossible these days.

Thank you!

**Comment by hvignolo87** [comment]
Hi Nicolas, hope you're doing well.

Some people reported the same issue these days. It seems like the site has changed in certain way that avoids automation. Unfortunately, right now I have no time to put hands on this so, if you can, please fork the repo and perform the changes in order to make it work.

Kind regards,

Hernán
